version: '3.8'

networks:
    job-hunter:
        name: job-hunter

services:
    php:
        volumes:
            - ./src:/var/www/html:delegated
        build:
            context: .
            dockerfile: php.Dockerfile
        container_name: php
        networks:
            - job-hunter
    mysql:
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 4306:3306
        image: mysql:5.7.32
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            - job-hunter
    nginx:
        container_name: nginx
        depends_on:
            - php
            - mysql
        volumes:
            - ./src:/var/www/html:delegated
        ports:
            - 80:80
            - 443:443
        build:
            context: .
            dockerfile: nginx.Dockerfile
        networks:
            - job-hunter

